package org.chummer.omae.model;

public enum GearCategory {

	AMMUNITION, ARMOR_ENHANCEMENTS, AUDIO_DEVICES, AUDIO_ENHANCEMENTS, BIOTECH,
	BREAKING_AND_ENTERING_GEAR, BTLS, CHEMICALS, COMMLINKS, COMMLINK_ACCESSORIES,
	COMMON_PROGRAMS, COMMUNICATIONS_AND_COUNTERMEASURES, CUSTOM, CYBERDECKS, DISGUISES,
	DOC_WAGON_CONTRACT, DRUGS, ELECTRONICS_ACCESSORIES, EXPLOSIVES, EXTRACTION_DEVICES,
	FOCI, FORMULAE, GRAPPLE_GUN, HACKING_PROGRAMS, ID_CREDSTICKS, 
}
