package org.chummer.omae.model;

public enum SkillGroupType {
	ACTING, ATHLETICS, BIOTECH, CLOSECOMBAT, CONJURING, CRACKING, 
	ELECTRONICS, ENCHANTING, ENGINEERING, FIREARMS, INFLUENCE, 
	OUTDOORS, SORCERY, STEALTH, TASKING;
}
