package org.chummer.omae.model;

public enum WeaponCategory {

	BLADES, CLUBS, IMPROVISED_WEAPONS, EXOTIC_MELEE_WEAPONS, EXOTIC_RANGED_WEAPONS,
	UNARMED, BOWS, CROSSBOWS, TASERS, HOLDOUTS, LIGHT_PISTOLS, HEAVY_PISTOLS,
	MACHINE_PISTOLS, SUBMACHINE_GUNS, ASSAULT_RIFLES, SPORTING_RIFLES, SNIPER_RIFLES,
	SHOTGUNS, LIGHT_MACHINE_GUNS, MEDIUM_MACHINE_GUNS, HEAVY_MACHINE_GUNS,
	ASSAULT_CANNONS, FLAMETHROWERS, LASER_WEAPONS, GRENADE_LAUNCHERS, MISSLE_LAUNCHERS,
	UNDERBARREL_WEAPONS
}
